### ISSUE TITLE
Use as cgm source (640G in suspend) clears IOB pill

### ISSUE THREAD

**Issue by LongboatAline** [pazaan/600SeriesAndroidUploader#201] opened 2018-02-20 15:59 UTC
When the 600series uploader is used as cgm-only (with the pump in suspend), and another pump in closed loop, the 600series uploader keeps clearing the IOB pill. This has the potential to affect bolus decisions, especially since the bolus calculator uses the IOB amount currently displayed in the pill as well.

#### Your Environment

* 0.5.1, 0.6.1-2
* Your Android Phone Model Name (e.g. Samsung J1 Ace):
* Android Version Number (e.g. use 4.4 for 4.4.4):
* WiFi
* 640G providing cgm data
* 754 controlled by Edison/openAPS for looping
* version 0.10.3-dev-20171205 head 1cd83e9d

#### Brief Explanation of Issue
Together with the devicestatus, if the 600 series pump is in suspend, the IOB (from the 640G) gets uploaded. 
The bolus calculator then disregards  the insulin already on board, and fails to substract it, leading to proposed amounts that are larger than needed or desired.

#### Steps to Reproduce (for bugs)

1. configure as cgm uploader only (I disregarded eons of progress and verified with 0.5.1 to make sure no treatment data was transferred yet)
2. use as cgm source for rig, have rig upload treatment data.
3. since both uploaders usually upload at an offset, watch the pump pill reflect the status of either uploader or rig, and the IOB pill toggle between 0 and whatever the rig considers as currently active IOB.

#### feature request:
* configurable modus toggle between "cgm uploader" and "pump"
* for those switching between pumps on a regular basis, it might be helpful to consider an automatic toggle between pump and cgm modus depending on suspend state of pump. (possible glitch: for uploading to carelink the pump cannot be suspended)

#### Severity Score

3-4 (I'm not yet sure if it affects oref0, I am optimistic though, that oref0 keeps its own track of IOB. The amount of IOB looked suspiciously low to me, but I don't have enough experience with it to blame this to the pill). It it affects the careportal bolus calculator only, it's at least subject to human review.

#### Screenshots:
1. 15:35:41 after upload from rig (antlia == pump). There's 0.36U of insulin on board. (actually, that one is from basal insulin only, see last image)
   ![15 35 41-rig-iob036](https://user-images.githubusercontent.com/35570803/36435689-a486b63e-1662-11e8-8d0c-41d353eec457.jpg)
1. 15:36:53 after cgm data upload from uploader, Pump pill and IOB are updated to reflect the view of the 640G
   ![15 36 53-uploader640g-iob0](https://user-images.githubusercontent.com/35570803/36435796-ec528006-1662-11e8-8763-0c4955e1537a.jpg)
1. 15:37:32 showing oref0 pill: bolus insulin is considered to be 0
   ![15 37 32-rig-iobfrombasalonly](https://user-images.githubusercontent.com/35570803/36435898-288ab930-1663-11e8-9920-25d12bcb6003.jpg)

**Comment by pazaan** [comment] 2018-08-11 05:26
Will make a setting to be able to support 3 modes:
* Pump and CGM
* CGM only
* Pump only

**Comment by pazaan** [comment] 2018-08-11 05:26
Also referenced in https://github.com/pazaan/600SeriesAndroidUploader/issues/62

**Comment by Pogman** [comment] 2019-01-06 17:18
As a workaround for now and to get you going... Install Android Studio, download the master from this repo and delete these lines and compile:

This stops the pump device status from being uploaded:

https://github.com/pazaan/600SeriesAndroidUploader/blob/07c55a4afa8a8245495aed896209846a4e9a5d22/app/src/main/java/info/nightscout/android/upload/nightscout/NightScoutUpload.java#L79

This stops treatments:

https://github.com/pazaan/600SeriesAndroidUploader/blob/07c55a4afa8a8245495aed896209846a4e9a5d22/app/src/main/java/info/nightscout/android/upload/nightscout/NightScoutUpload.java#L117-L120

And delete these lines to save the need for installing Crashlytics and Bugfender:

https://github.com/pazaan/600SeriesAndroidUploader/blob/07c55a4afa8a8245495aed896209846a4e9a5d22/app/src/main/java/info/nightscout/android/UploaderApplication.java#L62-L73

**Comment by tuzoenduro** [comment] 2019-01-10 12:50
@Pogman, it is done and installed... so far so good I have had no issues... Nightscout screamed at me a little because data from the pump was getting stale (from the 640) but it is all good now...

Thanks for the help!

Now if someone could help with integrating the CNL into openAPS so that we can read the bg values from the 640 directly from the rig that would be peachy... I'll hold my fingers crossed.

**Comment by Pogman** [comment] 2019-01-10 13:06
Ok cool... get a backback lol

Check out AndroidAPS too as there was supposed to be some integration for older Medtronic pumps via RileyLink but I don't know what state that's at.

**Comment by tuzoenduro** [comment] 2019-01-10 13:18
I did, good thing I already carry a bag to put my wallet, id and my sugar packets, but this is getting ridiculous.

I had checked AndroidAPS, but it always comes back to the same.. I only have the 640 as source of BGs for the moment, so I have to carry it with me... and if I want to interact with a loopable pump I need either an openaps rig or a rileylink. 

I would rather integrate the BG reading with the looping rig, so as to eliminate at least 1 electronic from my bag...

**Comment by HenrikHL** [comment] 2019-01-10 15:00
My understanding is that only older Medtronic pumps (522 with cirtain firwares) are compatible with AndroidAPS (and/or any other Loop-systems). It is possible to send information to these older pumps in order to deliver insulin.
With the 640 (and 670) it is only possible to get information from the pump - the protocol for sending info to the pump has not yet been broken
(I might be wrong)

**Comment by tuzoenduro** [comment] 2019-01-10 15:03
Hello Henrik, that is the idea.
I have a 640g with enlites which serves me as cgm source and a 722 which i use to loop. The problem is either androidapps or openaps require the cgm readings, and to get those i need an uploader phone for the moment. I would like to eliminate the need for this uploader phone by plugging the cnl to the rig and having it request the cgm from the 640.

Dr. luis toussaint
________________________________

**Comment by HenrikHL** [comment] 2019-01-10 15:25
This might be of interest to you:
https://github.com/pazaan/600SeriesAndroidUploader/issues/210

I (and a small group of people) are currently talking with Ascencia regarding making a "hardware device" in order to avoid having a CNL connected to a Phone via an OTG cable. The talk started 3 weeks ago - so no news yet...

**Comment by tuzoenduro** [comment] 2019-01-10 15:33
If you manage that out that would be awesome!!! I’ll follow this

Dr. luis toussaint
________________________________

**Comment by pazaan** [comment] 2019-01-10 21:03
@HenrikHL it will be interesting to see how that goes, though I expect that the decryption code in the CNL is probably the property of Medtronic, not Ascencia...

**Comment by HenrikHL** [comment] 2019-01-10 21:12
That is true - one of the things we have talked with Ascencia is that they make this Future device. They will not give us the decryption codes as they (Medtronic) sees Loop-systems as competators to their 670...
Another solution could be the combination of a CNL with a Raspberry or similar.
Maybe it could be possible to send "micro" bolus from CNL to Medtronic 640/670 - instead of managing the basal (which is not possible on these pumps...)

**Comment by Pogman** [comment] 2019-03-03 16:50
Rather then take an axe to everything for just CGM or PUMP, use a more fine grained approach and this way an advanced user can still get 'treatment' based details like alerts and dial in exactly what they want going to nightscout.

This is just going to be an option in the 'Advanced Nightscout Settings' menu to turn off the pump device status info that gets sent. That way for AAPS users they can still use all the other new features like pump alerts and estimated sgvs and so on, just no pump pill or anything to do with device status will get sent. As they only really use CGM they will get the graph and the occasional treatment event based on their settings. If a pump is being used without CGM then it will work as is and there is a 'cgm n/a' tag shown in the pump pill (if the device status option is enabled).

Additionally a treatment option to disable Basal events being sent to NS will be added. This way if you still want CAGE, IAGE, SAGE, BAGE or whatever you get those or not as options are already in place for them. With Basal disabled no suspend or temp will get sent. Pump alerts if enabled will get sent so you can see a history of these and they will not effect anything.

To round things off a disable Bolus option too... possibly redundant but logically fits for having full control.

**Comment by Pogman** [comment] 2019-03-03 16:50
![ns-upload-device-options](https://user-images.githubusercontent.com/7413594/53698432-7d88f700-3dd4-11e9-8a0d-fab7dc1d576f.jpg)

**Comment by Pogman** [comment] 2019-03-03 16:56
Actually with this a user can disable just the PUMP option here and still get the uploader battery. So an AAPS user would disable the Basal and PUMP options.

Additionally here you can see options for the device name: this will override the device name that the uploader generates - leave blank and it will still use that.

'Entered By' will get tagged to treatments if used.

A heartbeat is used when a cnl is unplugged to send updates and messages as needed rather then hard stop after this error state.

**Comment by LongboatAline** [comment] 2019-03-05 18:10
Thanks, this sounds perfect! I'm holding onto the last enlite sensor to be able to give that one  a test ride :-)

**Comment by Pogman** [comment] 2019-07-21 17:37
Closed - completed and available in 0.7.0 release

**Closed by Pogman** 2019-07-21 17:37 UTC
Labels: enhancement, in progress
