### ISSUE TITLE
IAGE (Insulin Age) is not automatically upadted when running the Indra branch

### ISSUE THREAD

**Issue by HenrikHL** [pazaan/600SeriesAndroidUploader#180] opened 2018-01-19 09:22 UTC
First of all - the Indra branch is phenominal - it is so much help to us parents. We don't need to go to our daugthers (12 years) pump in order to see how the day has been when she comes home from school. Also it is fantastisc during the night to know if the pump has stopped the Basal or started it again.

One thing I have noticed is that SAGE (Sensor Age) automatically updates when running the Indra branch. But IAGE (Insulin Age) is not beeing updated.

Either this is because I have done something wrong or the way the uploader sends IAGE data is not understood by nightscout? I was just wandering if this is a know issue - if anybody else than me experiences this - or what is needed from my side in order for this to work?

Bw,
Henrik - a very happy user!

#### Your Environment

* Uploader Version Number: Indra Branch
* Your Android Phone Model Name (e.g. Samsung J1 Ace):
* Android Version Number (e.g. use 4.4 for 4.4.4):
* Network Connection at the time the issue occurred (Wi-Fi, Mobile): Wifi
* (if relevant) Nightscout website version (e.g. 0.8.4 Funnel cake, master / dev branch): 0.10.0

#### Severity Score
1

**Comment by aboncher** [comment] 2018-01-19 09:28
You can use CAGE, canula age, instead of IAGE. The distinction between the two seems pretty gray.

**Comment by HenrikHL** [comment] 2018-01-19 09:36
Ok - thanx. My impression was that CAGE meant Cannula Age. We use a Cannula 2 years ago (before switching to pump) - that is why I have not included it in NightScout - I will do this going forward :-)

It would though be nice to know if it is a bug...

**Comment by cfaagaard** [comment] 2018-01-20 19:07
CAGE=Cannula Age -> in the careportal, if you create a "Log a treatment" where the event type is "Pump site change" you will get hours since the change in the CAGE.
IAGE=Insulin age ->  in the careportal, if you create a "Log a treatment" where the event type is "Insulin Cartridge Change" you will get hours since the change in the IAGE.
The pump-history in the 640/670 has events giving you the IAGE, but there is no event for CAGE. This you have to create yourself by using the careportal treatments.
Difference: sometimes you might just change the insulin without changing the cannula. And vice versa.

**Comment by Pogman** [comment] 2018-01-20 19:15
We send a CAGE treatment when the pump has a rewind event in the history data which should represent a reservoir fill and cannula change. If you enable the CAGE pill in NS it will show the hours since this last event.

**Comment by cfaagaard** [comment] 2018-01-20 19:18
@Pogman , should it not be IAGE treatment? You can make a cannula/infusion set change without changing the insulin. But the rewind event is always when you change the insulin (IAGE).

**Comment by Pogman** [comment] 2018-01-20 19:23
You could but it's not what people generally do and it's not recommended clinically - all the Medtronic literature talks reservoir/cannula change as a single event.

**Comment by cfaagaard** [comment] 2018-01-20 19:27
I read that :-) But sometimes we do this.... Sorry Medtronic.... fx a bad infusion set or extensive use of insulin

**Comment by Pogman** [comment] 2018-01-20 19:30
Also from the POV of what we have to work with - all we know is that a rewind happened so we have to pick one - it could be either one or even both. Sure it's a close call I guess...

**Comment by cfaagaard** [comment] 2018-01-20 19:33
I agree. In the begin I logged both IAGE and CAGE when a rewind happened. Now I just log the IAGE and then do the CAGE in the careportal, because of sometimes we do not change insulin and infusion set at the same time.

**Comment by cfaagaard** [comment] 2018-01-20 19:59
@Pogman : a side note. I use the event "CANNULA_FILL_DELIVERED" and not the "REWIND". Here I get some info about the change: AMOUNT_AFTER_PRIME and AMOUNT.

**Comment by Pogman** [comment] 2018-01-20 20:04
Sure yeah we've not mined everything in there.

BTW the RC branch is up and all going well this will be the official release in the coming days. A final testing round would be much appreciated to make sure the updates and fixes have not screwed anything up. This should be nice for any 670 users too now.

**Comment by cfaagaard** [comment] 2018-01-20 20:14
yes I saw the RC branch were up. Congrats!!! If I can find the time I will take it for a spin.

**Comment by HenrikHL** [comment] 2018-01-20 22:11
@Pogman - I am not quite sure I follow the logic in the CAGE vs IAGE you descrive above. If there is a rewind in the pump it can only be because of an Insulin cartidge change (otherwise there is no reason to do a rewind). I agree with you that whenever you do this you should both change Insulin and Infusion set. Why not send a IAGE treatment whenever there is a rewind?
If you don't do a rewind - but just change the infusion set (this could be because you have filled the reservoir too much or because the insertion point of the Infusion set is bad) then it would never be registered by the pump - and thus such a change would have to be inserted manually in nightscout.
To my knowledge (I might be wrong) the reason for changing the Infusion set is because the area where the infusion set is inserted in the body becomes "imune" to insulin. It is not because the Insulin becomes "old"...?

**Comment by Pogman** [comment] 2018-01-20 22:30
Sure this one of those things that go both ways and ultimately you end in semantics. There are lots of ways that a event can be triggered and the intent is not known. I was going to send both CAGE and IAGE and be done with it but went with CAGE and left it at that as I thought it better to leave the other for use as a manual entry for any use even as a timer or whatever. Maybe a user option to select for the the next version. 

Side note: insulin ages rapidly from sitting in the pump and close to the body - 37C/100F is like the sunny beach for insulin

**Comment by whooze** [comment] 2018-01-23 07:48
@Pogman I've been using the RC for a couple of days now and no problems so far!

**Comment by Pogman** [comment] 2018-01-23 13:26
Thanks @whooze  - there's one more RC to go with some last minute changes and that should be it.

**Comment by vincepf** [comment] 2018-01-28 13:43
I had a similar request as @HenrikHL . Despite the Medtronic recommendations, we rarely change my son's reservoir and site at the same time. His sites last a maximum of 2 days. It would be helpful if CAGE were updated with a cannula fill, and IAGE with a reservoir change.

 That being said, many thanks to all who have done this wonderful work. My wife and I are very grateful for your making the management of our son's health that much easier.

**Comment by Pogman** [comment] 2018-03-26 16:00
For those of you that change sites and insulin at different times can you confirm that this is the appropriate pump sequence?

A pump 'tubing fill' event will trigger a IAGE insulin change marker in NS.

A pump 'cannula fill' event (prime) will trigger a CAGE site change marker in NS.

**Comment by vincepf** [comment] 2018-03-26 19:45
Yes. Cannula fill should update the Cannula Age. Tubing fill (or reservoir rewind) should update the Insulin Age. My definition (not sure about Medtronic's) of 'Priming' is not a Cannula Fill, it is priming the tubing from the reservoir to the cannula connector.

**Comment by cfaagaard** [comment] 2018-03-27 08:47
@Pogman : just a tip. I use the cannula_fill_event (and PRIME_TYPE_NAME == canulla_fill) for creating both treatments (now). Every time there is a cannula_fill_event I send an "Insulin Change" to NS. If that cannula_fill_event has an insulin amount greater than zero there was also a cannula-change and I send a "Site Change" to NS.

**Comment by vincepf** [comment] 2018-03-27 13:07
@cfaagaard : Would this not reset the insulin age for just a site change?

**Comment by Pogman** [comment] 2018-03-27 13:41
What I used so far is the 'tubing fill' from the history data for IAGE as this can only happen when a 'new reservoir' is engaged on the pump.

The 'cannula fill' can be requested without a reservoir change and so this is used as CAGE.

Keep the feedback coming :)

**Comment by vincepf** [comment] 2018-03-27 14:35
Awesome! Thanks for all of your work on this invaluable tool!

**Comment by cfaagaard** [comment] 2018-03-27 17:55
@vincepf You are right. But I have not figured out how to determine if there is "new" insulin in the reservoir from the history-events. I found an example where I changed the insulin early morning (kid still sleeping) (this should only give me an IAGE) and changed the cannula later that day (with the same insulin) (this should only give me a CAGE). This gave me the following events (same patterns):
{25/03/2018 06.59.30 - INSULIN_DELIVERY_STOPPED 
{25/03/2018 07.00.09 - REWIND}
{25/03/2018 07.02.14 - CANNULA_FILL_DELIVERED - tubing_fill
{25/03/2018 07.02.15 - CANNULA_FILL_DELIVERED  - canulla_fill
{25/03/2018 07.02.15 - INSULIN_DELIVERY_RESTARTED

{25/03/2018 13.57.18 - INSULIN_DELIVERY_STOPPED 
{25/03/2018 13.57.38 - REWIND}
{25/03/2018 13.58.37 - CANNULA_FILL_DELIVERED - tubing_fill
{25/03/2018 13.58.39 - CANNULA_FILL_DELIVERED - canulla_fill
{25/03/2018 13.58.39 - INSULIN_DELIVERY_RESTARTED

**Comment by Pogman** [comment] 2018-03-27 18:02
@cfaagaard are you always getting a 'cannula fill' event after the rewind? ie you can not skip this event?

**Comment by cfaagaard** [comment] 2018-03-27 18:05
@Pogman just edited my previous answer with more info

**Comment by cfaagaard** [comment] 2018-03-27 18:06
@Pogman It looks like I get both events every time.

**Comment by Pogman** [comment] 2018-03-27 18:07
thanks good to know and data helps

**Comment by cfaagaard** [comment] 2018-03-27 18:10
@Pogman I thought of comparing the amount_after_prime with the amount from the status in mongodb to see if there was "new" insulin in the reservoir. But I do not think that would work.

**Comment by Pogman** [comment] 2018-03-27 18:18
We can use the >0 delivered to validate the cannula fill separate from the tubing fill for the CAGE and a tubing fill will always be IAGE.

**Comment by cfaagaard** [comment] 2018-03-27 18:34
Yes. but @vincepf is right. In my example I will get two IAGE and the last one is not "true". Not a problem on the same day. So fare it has not been an issue in my case. When I do change the cannula without a reservoir change, the reservoir runs out of insulin before it is too old.

**Comment by cfaagaard** [comment] 2018-03-27 18:38
@Pogman But I think the >0-solution is the only one that can give us the IAGE/CAGE automatically. So I would go for this and then get some feedback.

**Comment by Pogman** [comment] 2018-03-27 19:18
Ok so just looking back at these posts again.

When you do your 'site change only' ie CAGE are you doing it via the 'new reservoir' menu?

It looks like that from your data (I guess) and I would have expected that when just doing a site change the tubing portion gets disconnected from the body, a new cannula gets inserted, tubing reattached, 'fill cannula' clicked on the pump and your done.

This is what I did using 'quicksets' to get an idea of how IAGE/CAGE users would operate but yeah assumptions!

**Comment by cfaagaard** [comment] 2018-03-27 20:30
@Pogman hmmmm.... I have always done a "full" rewind (via the new reservoir menu) even if I only do a site change. Maybe I could do what you suggest :-) and then the 0>solution should work. I might try your way the next time and have a look at the data. (Kid is not home right now, so it is not possible to do some kid-debugging right now)

**Comment by vincepf** [comment] 2018-03-27 21:22
@Pogman We have never done a full rewind to just change a set. I don't know why you would. How can I capture the events when we change a set to show what is logged?

**Comment by Pogman** [comment] 2018-03-27 21:42
I don't really need anything captured, more to understand what people are physically doing when they do their changes.

**Comment by vincepf** [comment] 2018-03-27 22:02
For a reservoir change, we go to Options > Reservoir & Tubing > New Reservoir and proceed to follwo the instructions on the pump, namely: remove the old reservoir, install the full one, and prime the new tubing.
To only fill the cannula: Options > Reservoir & Tubing > Fill Cannula and just fill the cannula.
We don't manually stop delivery, as the pump will do so automatically when selecting either option.

**Comment by Pogman** [comment] 2018-03-28 21:47
@vincepf thanks, that method will always trigger precisely from the data in just the pump history.   

@cfaagaard I can see why you would do it your way too because if you don't you have a bit of tubing to hold on to after a site change and have to wait until a insulin change to use it and of course it's now out of it's sterile packet. But we can't detect it reliably from just the pump data, you can sort of imply it comparing the amounts from the previous changes but does not work for all cases.

So... will use detection based on vincepf use case and add a hint to the NS notes:

IAGE note: "Pump: new reservoir"
CAGE note: "Pump: fill cannula"

**Comment by vincepf** [comment] 2018-03-28 22:56
@Pogman Thanks again for your hard work. @cfaagaard If this creates an issue for your NS data, you may be able to refill the tubing without rewinding the reservoir by using the cannula fill option. You can adjust the amount of the fill. We use 2 units because our son uses the sure-t sets and we are filling the pigtail and steel needle. You may be able to simply adjust the amount for the cannula fill to fill the whole tubing. If not, even at 2 units per fill, depending on the length of the tubing, just a few fills would do it. The 23 inch tubing takes about 5 units to get to the pigtail.

**Comment by cfaagaard** [comment] 2018-03-29 02:32
@Pogman @vincepf 
I have been asking around how other people are doing this.
It very different how people do this. 

We are talking about this proces: https://hcp.medtronic-diabetes.com.au/sites/default/files/minimed_quick-set_infusion_set_guide.pdf

As I see it there are 3 main components in this:
- reservoir
- tube
- cannula

And apperently people change all three components independently at some point for different reasons.

- reservoir ("bad" insulin, no insulin left)
- tube (tube got a "crack")
- cannula (bent cannula, "bad" site)

I have not changed the tube independently. I have always seen tube/cannula as a "set". But I can see the scenario where you have good insulin and a new cannula and then the tube got a crack....

And this why I always have rewinded when I changed tube/cannula (and not the reservoir), because then I get the tube-filling and the cannula-filling option.
If you only change the cannula, and not the tube, I would do it like @vincepf  and use only the cannula-filling option. 
I have not tried using only the cannula-filling for a complete tube/cannula change (yet :-)).

So I guess what I am trying to say is that there lots of ways people are doing this. And I also think the 0>solution is ok.

thanks for the good discussion and the tips. See you :-)

**Comment by Pogman** [comment] 2018-03-29 13:19
@cfaagaard thanks this has been very helpful.

Thinking about adding a uploader setting for a user defined threshold value that can trigger the IAGE.

'auto' = a 'new reservoir' pump event will trigger a IAGE (as previously discussed) default setting
'1.8ml' = 140U 
'3.0ml' = 240U
'nnn' = user defined value, set to whatever suits

A 'tubing fill' pump event gives us the prime amount + remaining. If >threshold IAGE is triggered.

A 'canula fill' pump event >0 triggers a CAGE.

**Comment by cfaagaard** [comment] 2018-03-30 09:58
@Pogman 
happy to help.

"Change component" user scenarios:

- Change only reservoir (do a rewind, 0 in tube-filling and 0 in cannula-filling)
- Change only tube (1. do a rewind, 5-8 in tube-filling and 0 (maybe) in cannula-filling OR 2. use the cannula-filling for filling the tube and the cannula (have not tried this))
- Change only the cannula (use the cannula-filling option, 0.3 (or something like that) in cannula-filling.

I also think that some cannula do not need to be filled. (so you might also want to have the 'cannula fill"-value in the setting. -> this one: "A 'canula fill' pump event >0 triggers a CAGE."

And if we look at the data in the history events there is no way to make a 100% match between the user scenarios, history-data and NS's IAGE/CAGE.
I think your proposed solution is the best, but it is not a 100%.

**Comment by vincepf** [comment] 2018-03-30 10:18
I believe it would be best practice to trigger a IAGE reset at each rewind. Our son has been pumping for 3 years and we have never had a need to change only the tubing. @cfaagaard is correct, the  sure-t set, if changed along with the tubing, can be filled along with it, with no separate cannula fill. In such a case, filling the tubing only and using cannula fill for the rest would trigger the CAGE reset. If users were instructed to do so for those situations, that might be helpful.

**Comment by cfaagaard** [comment] 2018-03-30 10:39
@Pogman @vincepf  So for CAGE: maybe the "cannulafill>0" should be a cannulafill==SettingParameter?

**Comment by Pogman** [comment] 2018-03-30 22:37
Hmmm...

And even with myself I occasionally forget to do the 0.3 cannula fill and don't sweat it due to being such a small amount (for me).

**Comment by cfaagaard** [comment] 2018-03-31 07:33
@Pogman  same here :-) (that is why I until recently did the CAGE-update through the careportal. And thinking about going back....)

**Comment by shawnbissell** [comment] 2019-03-01 06:07
I can confirm this is working well in the WIP 0.7.0 branch with NS v0.11.1.

**Comment by Pogman** [comment] 2019-07-21 17:44
Closing this out now as release approaches. Hopefully this is going to work out useful for those that need it. If you do use the IAGE feature and can offer setting up tweaks to less technical users please get on the FB group.  A small guild to best use would be great too.

**Closed by Pogman** 2019-07-21 17:44 UTC
Labels: enhancement, in progress
