### ISSUE TITLE
Can't Register Contour Next Link

### ISSUE THREAD

**Issue by AusRedMonkey** [pazaan/600SeriesAndroidUploader#116] opened 2017-04-18 20:46 UTC
* Uploader Version Number: **0.4.0/9eb755e**
* Your Android Phone Model Name: **Xperia XA (F3111)**
* Android Version Number: **6.0**
* Network Connection at the time the issue occurred: **WiFi & Mobile**

#### Brief Explanation of Issue
Can not get any information from the CNL to the uploader. Uploader find CNL and connects but can not register

#### Steps to Reproduce (for bugs)
1. Followed installation guide in relation to CNL data upload to CareLink site, turned off Remote Bolus, etc.
2. Connected CNL with USB OTG cable and accept USB permission in the Uploader.
3. Status says' Connected to Contour Next Link on Channel ..'
4. Registered devices tab says 'To register a Contour Next Link you must first plug it in, and get a reading from the pump.'

I recently found this app and really want to get it going to get my wife's pump data into both Nightscout and xDrip+, but am having some issues with the registration of the device it seems in the uploader.

I have downloaded an OTG Troubleshooter app and it states that the phone has OTG capability and when connecting a normal USB drive everything works fine and the troubleshooter says everything is OK; so this tells me the phone can handle OTG and also the cable is OK.
When I do the same with the CNL however, the trouble shooter basically tells me that no mass storage device is connected but OTG detected.

When the CNL is connected to the phone, the screen on the CNL just shows a 'charging/charge complete' screen. As I have never had it working I'm not sure if this is normal or not.

Interestingly, I have also tried on version v0.3.1 of the uploader. It seems to find the device and serial number, etc. After entering the CareLink details it seems to register, however nothing happens after that, says its connected on channel ... but not data is transferred.

Any help would be appreciated. I have looked through others open and closed issues on here can't seem to find a solution.

**Comment by pazaan** [comment] 2017-04-18 21:26
My first guess is that the app can't decrypt the packets from the CNL - is the CNL paired with the pump? Are you able to send a remote bolus from the CNL to the pump?

**Comment by AusRedMonkey** [comment] 2017-04-19 16:48
Hi Lennart

Yes the CNL is paired with the pump and is able to remote bolus. In addition we transferred the pump data with the CNL to the Medtronic CareProtal , so appears that the connection between the pump and the CNL is working OK.

**Comment by Tausta** [comment] 2017-04-19 19:05
We are using Sony Xperia XA (F3111) with uploader. Are you using sensor with pump? I think that uploader needs sensor SG values. Issue #108.

**Comment by pazaan** [comment] 2017-04-19 20:26
The next update will have support for uploading data without CGM data.

**Comment by pazaan** [comment] 2017-04-19 20:27
Duplicate of #108

**Closed by pazaan** 2017-04-19 20:27 UTC
