### ISSUE TITLE
Ability to choose data to upload to Nightscout

### ISSUE THREAD

**Issue by sjolundjohn** [pazaan/600SeriesAndroidUploader#62] opened 2016-06-22 13:54 UTC
Hi,

I occasionally use different sensors (such as Dexcom) or an old pump for experimentation purposes. For this reason, I am having multiple and conflicting data go up to Nightscout sometimes.

Therefore, I would love the option, in the app, to be able to select which fields are uploaded to Nightscout. All by default, but then you can deselect fields such as:
BG
IOB
Basal

Thanks for the great work!
#### Severity Score

2

**Comment by pazaan** [comment] 2018-08-11 05:26
I don't think we want to be able to deselect specific fields, since this would be a LOT of work for an unknown value, but I think we could certainly support a the following modes:
* Pump and CGM
* CGM only
* Pump only

Closing as a duplicate of https://github.com/pazaan/600SeriesAndroidUploader/issues/201

**Closed by pazaan** 2018-08-11 05:26 UTC
Labels: enhancement
