### ISSUE TITLE
Nightscout site is not available if AUTH_DEFAULT_ROLES=denied

### ISSUE THREAD

**Issue by j144** [pazaan/600SeriesAndroidUploader#184] opened 2018-01-26 19:45 UTC
RC1 worked fine when nigthscout AUTH_DEFAULT_ROLES=denied, but release throws error. If AUTH_DEFAULT_ROLES is set to read , uploader works fine.

From NG log (heroku/papertrail): 
DENIED:   xx.xx.xx.xx no-token api:status:read 
at=info method=GET path="/api/v1/status.json"

**Comment by Pogman** [comment] 2018-01-26 19:48
we need to be able to read the status

**Comment by Pogman** [comment] 2018-01-26 19:49
actually we don't send a token for it but maybe we should

**Comment by j144** [comment] 2018-01-26 20:10
Seems to work with AUTH_DEFAULT_ROLES=status-only.

**Comment by Pogman** [comment] 2018-01-26 20:24
Well it's a good catch as I think this may be the cause of some of the issues we're seeing for some users on FB.

**Comment by Pogman** [comment] 2018-01-27 02:45
*** fixed in v6.1

**Comment by Pogman** [comment] 2018-02-04 14:00
closing fixed and released in v0.6.1

**Closed by Pogman** 2018-02-04 14:00 UTC
