### ISSUE TITLE
E86 Software error (on CNL)

### ISSUE THREAD

**Issue by wright-david** [pazaan/600SeriesAndroidUploader#61] opened 2016-06-17 20:18 UTC
Experienced E86 Software error at 2am one night, with what was believed to be a good USB OTG cable.
- Uploader Version Number: 0.2.1
- Your Android Phone Model Name: Moto G 2nd Gen
- Android Version Number: 5.0

**Comment by pazaan** [comment] 2016-06-17 21:35
What does E86 mean?

**Comment by mwalting** [comment] 2016-06-19 18:36
Hi Pazaan,

first of all many many thanks for all your engagement, we love this tool so much! 

We'd this Error message sometimes on our Bayer Contour Device and the message was something about a Hardware/Software failure and we've to restart this device. Just replug it again to the OTG Phonecable and everything works fine again.

Uploader Version 0.2.1
Android Phone: Samsung S3 (Android Version 4.3)

**Comment by pazaan** [comment] 2016-07-03 03:58
How frequent is this? Is it possible to reproduce?

**Comment by wright-david** [comment] 2016-07-03 20:33
Sorry for being extremely obscure in the fault description - though I'm astonished if you've never seen this error yourself.

I only saw this error once in 4 or 5 nights running, and unfortunately have no leads on how to reproduce it with the uploader. 

However in early hacking attempts, I could induce it by sending 'malformed' data to the CNL.
![e86](https://cloud.githubusercontent.com/assets/14233575/16547437/b0d92cb0-4165-11e6-819b-bbd57918b9fc.png)


However as timwa124 says, it requires power reset of the CNL to clear the problem.

**Comment by timwa124** [comment] 2016-07-05 07:36
Hi David,

the last 1,5 weeks i had a lot of trouble with the CGM because the pump randomly showed just "---" as a value. This happens sometimes for 5min and sometimes for up to 30min. Therefore i requested a change of the transmitter and Medtronic gave me a new one.
After this change i didn't get any "---" Error and as well the E86 Error is gone. if this will happen  again, i'll inform you again...

BTW Thanks for 0.3.1! It's a great App, (ok sometimes it stop working after a battery change) but for the rest of our time it works very well

best

**Comment by Pogman** [comment] 2016-07-05 11:21
@timwa124 Hi I'm getting a lot of the same problems with "---" on the pump for 5-30 mins but this really only happens while the uploader is in use. It was felt that this might be due to some sort of local interference but now I wonder if it's just that or some issue related to the transmitter.

Can you tell me if you were have the same "---" problem when you were not using the uploader? How often did the E86 error show up - I see occasionally but rare enough to be a concern.

**Comment by timwa124** [comment] 2016-07-05 11:58
@Pogman 
it seems you're in the same trouble like we were. i called medtronic (without speak about nightscout because i thought it's a bad idea to talk about this :) and talked about our problems with the transmitter and the pump. they agreed to change the transmitter by sending a new one. as well they stated about some inteference if you have a Babyphone very close to the Person with Pump and CGM. There was an internal eMail at medtronic talked about this and a patient told them this caused the issue about the lost signal with "---".
for me this was not only related to the android uploader, sometimes when i tried to use the carelink software to read the data, this happend as well.

i changed a lot now, and until today i got no issue anymore after replacing the transmitter by our hospital (via medtronic)
#1 disabled 2.4Ghz completly and just use 5Ghz
#2 The android phone use LTE to upload the data (will be evaluated with 5Ghz Wifi in the future)
#3 changed the transmitter 
#4 babyphone was disabled in the first stage but is reactivated now and cause no problems.

i think the error E86 occurs only if you try to collect the data manually (by pressing the get data button) and there is no data available on the pump ("---"). then i got this errormessage. during the day without my interaction i had never an E86 Error message.

BTW: I read a lot about this topic at the internet and many people recommended to change the transmitter and give it a try. 

if you wanna talk offline just send me a email to timwa321@gmail.com. btw: where are you from? seems you on a similar timezone like me (Germany) :)

**Comment by Pogman** [comment] 2016-07-05 12:16
@timwa124 Thanks for the info! Time to get on to Medtronic and see if I can get a new transmitter out of them. BTW I had turned off every 2.4 device I have including the phone and just run the uploader via a Android emulator on PC and I was still getting this issue. Only interference left after that was from the neighbour. Also i note that all phones these days tend to send out probes all over the 2.4 spectrum (I can see it on my spectrum survey tool) and even passing cars will cause some noise (phones everywhere!).

I wonder if there is a difference in transmitter versions - I have 2.0.C here (via sensor menu in the status bar). Is there a difference between your old and new transmitter versions?

**Comment by timwa124** [comment] 2016-07-05 19:01
@pazaan 
today i just activated my wifi on this android phone and i got the E86 Message again. Just after 5min. see screenshot of my stick and phone.

i just attached a picture of this error message incl. the error on my android phone.
![c519d9ca-600b-4fc3-bd16-0f0f815ea4e2](https://cloud.githubusercontent.com/assets/19916956/16596285/801e7c8a-42f3-11e6-9178-979d2ea5cf9c.jpeg)

**Comment by volkerrichert** [comment] 2016-12-18 19:38
Shit.... It was #68. :-(

**Comment by volkerrichert** [comment] 2017-03-27 18:02
i this still relevant? i know this error, but haven't seen it since month.

**Comment by pazaan** [comment] 2017-03-27 22:17
I never saw it myself, @Pogman?

**Comment by Pogman** [comment] 2017-03-28 01:15
This is hugely reduced due to clearing unexpected messages but there is still potential for rare CNL errors.

Can happen with a very weak signal (RSSI < 5) where it's possible that the CNL and where the uploader thinks it should be it terms of comms gets confused. I have a few small changes that I was going to PR that should help in this situation (give me a day or 2).

If there is still an issue around this I would look at dropping any time+status comms for rssi < 5 and sending a "weak signal" message to user.

Hard to test for this! I got lucky before during the time when I was getting a lot of channel changes and noticed that on channel 26 (way off the end of the wifi range) that the pump-cnl signal quality is quite reduced and the pump would often resend the same message causing an error and cnl crash.

**Comment by seven4774** [comment] 2017-05-18 07:54
We get this quite regularly on channel 26 and then get the reciprocal error of E86 on the carelink device. only solution I have found so far is clear data from device and restart it

**Comment by Pogman** [comment] 2019-07-21 18:15
There are load of improvements to CNL stability for very rare edge cases in version 0.7.0

This has had months of endless stress tests and there doesn't seem to be anything left to discover and I've tried. In general use it now runs endlessly 24/7 without a hitch.

Closing... but feel free to jump back in

**Closed by Pogman** 2019-07-21 18:15 UTC
Labels: bug, question

**Comment by obodeldog** [comment] 2019-07-25 21:42
Hi. We just tried the project and we have also the E86 mistake.

**Comment by Pogman** [comment] 2019-07-25 21:49
Are you using the beta version? Almost all E86 issues are related to the usb cable and connection to a device running the uploader.

**Comment by obodeldog** [comment] 2019-07-26 04:23
I used 0.6.1. The cable is a new one. Do you really think the cable is the problem?

**Comment by Pogman** [comment] 2019-07-26 12:49
CNL errors should be relatively rare even with 0.6.1 specially for a uploader device that is kept in range of the pump most of the time.

Errors on the CNL such as E86 that require the CNL to be unplugged and plugged back in are mostly caused by a disturbance while comms are in progress. The connection between meter and uploader needs to be secure at all times with no wobble or looseness on the usb port which can happen when on the move. Cables can get worn out or even the usb port itself can get worn out. The connections in the plugs and sockets are tiny.
