### ISSUE TITLE
 Reduce messages over to the air

### ISSUE THREAD

**Issue by Tausta** [pazaan/600SeriesAndroidUploader#126] opened 2017-07-09 15:41 UTC
To reduce messages over to the air, getPumpTime should not be called on every poll.
It is useless to get pump time, if:
 - status message does not contain SGV
 - SGV time is as expected (compared to the previus time and phone time,  +- 2 seconds). In this case pumpOffset can be same as in previous record.

**Comment by Pogman** [comment] 2017-07-09 16:00
The pump time is constantly drifting forward in time at around 30 seconds per week.

I have a test version that only gets time every 4 hours and this is fine and handles the drift but there are various scenarios that need to be dealt with for production use. The actual battery saving was disappointing.

**Comment by Tausta** [comment] 2017-07-09 16:12
Battery saving is one point, but the main idea is to increase reliability. It is frustrating that if status message has been received correctly but time message fails.

**Comment by Pogman** [comment] 2017-07-09 16:16
This has been tested too and status message will fail if time message is not in use. The reason for this is radio noise or pump occlusion at time of comms. It's normal and the poll will try again in 60 seconds.

**Comment by Tausta** [comment] 2017-07-09 17:05
We have several "Communication Error: Invalid message received for getPumpTime". It is the most common cause of failure (if the connection is established).

**Comment by Pogman** [comment] 2017-07-09 17:12
I get these most days and occasionally a few in a row. Depending on your environment and use these will vary. The radio in the pump is super low power and takes very little to cause an error. What radio channel is being connected? channel 26 is really bad for seeing a lot of these errors.

**Comment by Tausta** [comment] 2017-07-09 17:40
Today has been in use channel 14. I know that sometimes our home is very noisy. Especially PS4 generate a lot of BT traffic. In noisy environment it is important that this application transfers over to the air as little as possible and as fast as possible.

**Comment by Pogman** [comment] 2017-07-15 19:04
Hi @Tausta can you try out the latest develop code and see if there are any improvements to comms errors in your environment?

**Comment by Tausta** [comment] 2017-07-16 18:04
Very limited tests done without PS4. Not anymore ""Communication Error: Invalid message received for..". Only few "Timeout communicating with the Contour Next Link / Pump" and two consecutive "Error decrypting messages from Contour Next Link". Much better than before!

Also one issue with next poll calculation: 
![image](https://user-images.githubusercontent.com/23084001/28250063-cb477a06-6a69-11e7-9e66-b0df66507dd8.png)

**Comment by Pogman** [comment] 2017-07-16 19:34
ok - I messed up a commit and it's been sorted today, the latest dev branch is fully up to date now and that was probably the cause of the poll time going wrong

Good feedback there - that decrypt bug wasn't caught before and would crash the app, nice to see it's getting it now as part of the new fixes.

The fails you see now are expected and handled but should be less overall.

**Comment by Pogman** [comment] 2017-07-16 19:46
When you got the decrypt error did it recover and read sgv at the next poll?

**Comment by Tausta** [comment] 2017-07-16 21:57
Yes, it recovered and next poll was successful.

**Comment by Pogman** [comment] 2017-07-17 00:44
That's good! I've never gotten a decrypt error. If you get these a lot it might be a good chance here to see what's causing them.

**Comment by Tausta** [comment] 2017-07-18 08:19
Got first with more information:
![image](https://user-images.githubusercontent.com/23084001/28307177-ad46b476-6baa-11e7-8ba7-660184bb22cb.png)

**Comment by Pogman** [comment] 2017-07-18 18:10
It might have something to do with a weak signal. It cancels at RSSI < 5% but if that happens a lot may need to think about increasing it.

BTW there were still problems with poll time - pushed some more changes for that into develop.

**Comment by Pogman** [comment] 2018-02-02 20:51
closing - n/a to for v0.6+

**Closed by Pogman** 2018-02-02 20:51 UTC
