### ISSUE TITLE
abnormal consumption of the transmitter battery, continuous loss of connections between the sensor and the pump.

### ISSUE THREAD

**Issue by francopor** [pazaan/600SeriesAndroidUploader#113] opened 2017-04-09 08:11 UTC
abnormal consumption of the transmitter battery, continuous loss of connections between the sensor and the pump

* Uploader Version Number:0.4.0
* Your Android Phone Model Name Samsung Galaxy S4
* Android Version Number 5.0.1
* Network Connection at the time the issue occurred Wi-Fi en Mobile

I use 640g-upload Android v0.4.0
I was very satisfied, but after a month of use I found some problems:

abnormal consumption of the transmitter battery,
continuous loss of connections between the sensor and the pump.

I do not know how to explain how it is possible.

**Comment by pazaan** [comment] 2017-04-09 08:13
Can you please be a bit more specific? It would be good to have specific measurements and outcomes. For example, how long does the transmitter battery last when you're not using the uploader? How long does it last when you are using the uploader?
The loss of connections between sensors are already covered in other issues, and will be improved in the next update.

**Comment by francopor** [comment] 2017-04-09 10:16
how long does the transmitter battery last when you're not using the uploader? 6 day minimum
How long does it last when you are using the uploader? 3 day

Sorry for my english


Da: Lennart Goedhart [mailto:notifications@github.com]
Inviato: domenica 9 aprile 2017 10:14
A: pazaan/640gAndroidUploader <640gAndroidUploader@noreply.github.com>
Cc: francopor <francopor@msn.com>; Author <author@noreply.github.com>
Oggetto: Re: [pazaan/640gAndroidUploader] abnormal consumption of the transmitter battery, continuous loss of connections between the sensor and the pump. (#113)


Can you please be a bit more specific? It would be good to have specific measurements and outcomes. For example, how long does the transmitter battery last when you're not using the uploader? How long does it last when you are using the uploader?
The loss of connections between sensors are already covered in other issues, and will be improved in the next update.

**Comment by Pogman** [comment] 2017-04-09 19:10
Hey - the transmitter battery draining faster is a consequence of the pump changing radio channels needing a re-sync from the sensor and thus using up the tiny battery fast. The next version of the uploader does not trigger channel changing and the transmitter battery will last as long as normal.

**Comment by pazaan** [comment] 2017-07-24 14:56
@francopor @Pogman Can you both confirm whether this issue should be left open, or can be closed now?

**Comment by Pogman** [comment] 2017-07-24 15:49
As far as I'm concerned the uploader does not cause this issue anymore.

Note: If the pump loses the sensor due to being out of range or obscured by the body etc then you will notice that the transmitter battery will get used up faster as it uses power to find pump again. This has nothing to do with uploader.

**Comment by Pogman** [comment] 2018-02-02 20:56
closing as this is not an issue caused by the uploader and no further response from the user.

**Closed by Pogman** 2018-02-02 20:56 UTC
